require:
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ModuleFunction:
  Enabled: false
